baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

title: An (Un)official Website - Integrated Science Education and Research Centre (ISERC) 

permalink: /:categories/post/:slug
# Build settings
iis_slider_array: []
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-lunr-js-search
  - jekyll-minifier
